name: PR Check

on:
  pull_request:
    branches:
      - development
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-x86_64-linux
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Set up nix dev shell
        run: nix run .#nix-develop-gha -- .#ci-shell

      - name: Jest & type check
        run: |
          set -euo pipefail
          yarn install
          npx expo-doctor
          yarn lint
          yarn test
