insert into bounds (
        observed,
        geom,
        everything,
        bounds,
        minlon,
        minlat,
        maxlon,
        maxlat
    )
values (
        datetime(),
        st_envelope(
            makeline(
                makepoint(
                    $json->'bounds'->>'minlon',
                    $json->'bounds'->>'minlat',
                    4326
                ),
                makepoint(
                    $json->'bounds'->>'maxlon',
                    $json->'bounds'->>'maxlat',
                    4326
                )
            )
        ),
        $json,
        $json->'bounds',
        $json->'bounds'->'minlon',
        $json->'bounds'->'minlat',
        $json->'bounds'->'maxlon',
        $json->'bounds'->'maxlat'
    );